spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

blockchain:
  rpc-endpoint:
    bok: ${BOK_RPC_ENDPOINT:http://10.10.1.35:8545}
    wr: ${WR_RPC_ENDPOINT:http://10.10.1.91:8545}
    sh: ${SH_RPC_ENDPOINT:http://10.10.1.122:8545}
    hn: ${HN_RPC_ENDPOINT:http://10.10.1.49:8545}

logging:
  level:
    root: WARN
    org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl: ERROR
