spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN

app:
  cors:
    allowed-origins:
      - # CloudFront 주소 확정 후 작성

wallet:
  key-cipher:
    secret: ${WALLET_KEY_CIPHER_SECRET}
